// @generated by ts-typegen -- DO NOT EDIT
/**
 * The JSON wire shape of an admin user listing row. `UserRole` has no serde
 * impl (it's only a `sqlx::Type`), so we map to explicit string fields here.
 */
export interface AdminUser {
  id: string;
  name: string;
  role: string;
  totp_enabled: boolean;
  created_at: string;
  last_login: string | null;
}
