// @generated by ts-typegen -- DO NOT EDIT
/**
 * The type-specific fields of a `book_review` post.
 */
export interface BookReview {
  book_title: string;
  author: string;
  rating: number | null;
  cover_url: string | null;
  isbn: string | null;
  read_date: string | null;
  link: string | null;
}
