// @generated by ts-typegen -- DO NOT EDIT
import type { City } from "./City";

export interface Country {
  country: string;
  population: number | null;
  gdp: number | null;
  image: string;
  flag: string | null;
  cities: City[];
}
