// @generated by ts-typegen -- DO NOT EDIT
/**
 * The id a client should navigate to. No room exists yet — it is created by
 * the first stream that opens on it.
 */
export interface CreatedRoom {
  id: string;
  title: string;
}
