// @generated by ts-typegen -- DO NOT EDIT
import type { Commit } from "./Commit";
import type { Detail } from "./Detail";
import type { PostSummary } from "./PostSummary";
import type { Profile } from "./Profile";
import type { Project } from "./Project";

export interface Home {
  profile: Profile;
  projects: Project[];
  commits: Commit[];
  posts: PostSummary[];
  book_reviews: PostSummary[];
  details: Detail[];
}
