// @generated by ts-typegen -- DO NOT EDIT
/**
 * One entry of an `RTCConfiguration`'s `iceServers`.
 */
export interface IceServer {
  urls: string[];
  username: string | null;
  credential: string | null;
}
