// @generated by ts-typegen -- DO NOT EDIT
/**
 * The public JSON shape of a user — never carries the pin hash or TOTP secret.
 */
export interface Me {
  id: string;
  name: string;
  role: string;
  totp_enabled: boolean;
}
