// @generated by ts-typegen -- DO NOT EDIT
export interface NoteLink {
  slug: string;
  /**
   * `None` when the target doesn't exist yet — a dangling link.
   */
  title: string | null;
  id: string | null;
}
