// @generated by ts-typegen -- DO NOT EDIT
import type { MetaEntry } from "./MetaEntry";
import type { NoteLink } from "./NoteLink";

/**
 * One note in full, with everything the reader needs in a single request.
 */
export interface Note {
  id: string;
  slug: string;
  title: string;
  body: string;
  tags: string[];
  /**
   * Every name this note answers to, primary first.
   */
  names: string[];
  udf: MetaEntry[];
  links: NoteLink[];
  backlinks: NoteLink[];
  created_at: string;
  updated_at: string;
  /**
   * Non-fatal problems from the last save (empty on a plain read).
   */
  notices?: string[];
}
