// @generated by ts-typegen -- DO NOT EDIT
import type { MetaEntry } from "./MetaEntry";

/**
 * A list entry. Deliberately without the body: the browser, quick switcher and
 * `[[link]]` autocomplete all work from this, and shipping every note's full
 * text to a phone to render a sidebar would be wasteful.
 */
export interface NoteIndexEntry {
  id: string;
  /**
   * `None` for a soft-deleted note: deletion releases its names so they can
   * be reused straight away, which means a trashed note genuinely has no
   * address until it is restored. Nullable rather than an empty string so a
   * client can't accidentally build `/secret/notes/` out of it.
   */
  slug: string | null;
  title: string;
  tags: string[];
  /**
   * Every name, primary first. Carried in the index so the client can
   * resolve a `[[link]]` written against a superseded name without a round
   * trip — otherwise the reader would show it dangling while the server
   * resolved it perfectly well.
   */
  names: string[];
  /**
   * User-defined properties, so the browser can filter on them without a
   * second round trip. Filtering happens client-side over this list (as tag
   * and title search already do), which also keeps the counts shown in the
   * filter menu consistent with the rows actually listed.
   */
  udf: MetaEntry[];
  excerpt: string;
  created_at: string;
  updated_at: string;
}
