// @generated by ts-typegen -- DO NOT EDIT
import type { Sources } from "./Sources";

/**
 * Another participant, as announced to the room and carried in the roster.
 * Ids are stringified here, at the serialization boundary, as everywhere else
 * in the API.
 */
export interface PeerSummary {
  peer_id: string;
  name: string;
  seq: number;
  sources: Sources;
}
