// @generated by ts-typegen -- DO NOT EDIT
import type { BookReview } from "./BookReview";
import type { PostType } from "./PostType";

/**
 * The full JSON wire shape of a post (admin views and the public detail page).
 */
export interface Post {
  id: string;
  slug: string;
  title: string;
  body: string;
  is_published: boolean;
  published_at: string | null;
  created_at: string;
  updated_at: string;
  post_type: PostType;
  book_review?: BookReview;
}
