// @generated by ts-typegen -- DO NOT EDIT
/**
 * The kind of a post. `Article` is a plain markdown post; `BookReview` carries
 * an extra [`BookReview`] payload from the `book_reviews` side table. A new
 * type slots in here plus, optionally, its own side table and payload struct.
 */
export type PostType = "article" | "book_review";
