// @generated by ts-typegen -- DO NOT EDIT
import type { BookReview } from "./BookReview";
import type { PostType } from "./PostType";

/**
 * A public list entry: no body, just a raw-markdown excerpt for the card, plus
 * the type and a light book-review summary so cards can style reviews.
 */
export interface PostSummary {
  slug: string;
  title: string;
  excerpt: string;
  published_at: string | null;
  post_type: PostType;
  book_review?: BookReview;
}
