// @generated by ts-typegen -- DO NOT EDIT
/**
 * `seo_title` / `seo_description` are the home page's search-result copy. Both
 * are allowed to be empty, and empty means "use the build-time default baked
 * into `index.html`" — see `VITE_SITE_TITLE` / `VITE_SITE_DESCRIPTION` in
 * `frontend/.env`. That's why they're plain `String` rather than `Option`: the
 * frontend only ever asks "is this blank?", and a blank string answers it.
 */
export interface Profile {
  intro_markdown: string;
  profile_image_url: string;
  github_url: string;
  seo_title: string;
  seo_description: string;
}
