// @generated by ts-typegen -- DO NOT EDIT
export interface Project {
  id: string;
  name: string;
  description: string;
  url: string | null;
  repo: string | null;
  sort_order: number;
  tags: string[];
}
