// @generated by ts-typegen -- DO NOT EDIT
/**
 * A room as the lobby sees it. Timestamps are stringified here, at the
 * serialization boundary, as everywhere else in the API.
 */
export interface RoomSummary {
  id: string;
  title: string;
  started_by: string;
  started_at: string;
  people: number;
}
