// @generated by ts-typegen -- DO NOT EDIT
/**
 * What a peer is currently publishing. Four flags for the four fixed
 * transceivers, so a tile can say "camera off" rather than show a black
 * rectangle and hope.
 */
export interface Sources {
  mic: boolean;
  app: boolean;
  camera: boolean;
  screen: boolean;
}
