// @generated by ts-typegen -- DO NOT EDIT
import type { DayCount } from "./DayCount";
import type { HourCount } from "./HourCount";
import type { KindCount } from "./KindCount";
import type { RouteCount } from "./RouteCount";

export interface Stats {
  total: number;
  /**
   * Distinct client IPs — an aggregate count only; no IP is ever returned.
   */
  unique_visitors: number;
  /**
   * The page the aggregates are filtered to, echoed back, or `null` when the
   * counts span all pages.
   */
  route: string | null;
  per_day: DayCount[];
  by_kind: KindCount[];
  by_hour: HourCount[];
  /**
   * The busiest pages overall — always spans all pages, so it stays a stable
   * menu even when the other aggregates are filtered to one `route`.
   */
  by_route: RouteCount[];
  /**
   * Non-page routes that look like static-asset fetches (`/chip.svg`,
   * `/assets/bundle-523fsdg.js`, a `.css`) — real resource loads, not spam.
   * Kept out of every page count above. Always spans all pages.
   */
  static_total: number;
  /**
   * The most-hit static-asset paths. Always spans all pages.
   */
  by_static_route: RouteCount[];
  /**
   * Non-page routes that are robot/scanner noise — probes at nonexistent
   * paths, plus crawler fetches of `/robots.txt`/`/sitemap.xml`. Kept out of
   * every page count above. Always spans all pages.
   */
  robot_total: number;
  /**
   * The most-hit robot paths, so the noise is inspectable rather than just a
   * number. Always spans all pages.
   */
  by_robot_route: RouteCount[];
}
