// @generated by ts-typegen -- DO NOT EDIT
/**
 * The JSON wire shape of a detailed visit row.
 */
export interface Visit {
  id: string;
  created_at: string;
  kind: string;
  route: string | null;
  /**
   * How the route classifies: `page`, `static` (asset fetch), or `robot`
   * (bot/scanner noise). Lets the admin table flag robot hits red without
   * re-deriving the rules client-side — one source of truth in `visit_class`.
   */
  class: string;
  client_ip: string;
  user_agent: string;
}
