// @generated by ts-typegen -- DO NOT EDIT
import type { Visit } from "./Visit";

/**
 * A page of detailed visits plus the total matching the current filters, so the
 * client can drive prev/next controls.
 */
export interface VisitsPage {
  total: number;
  limit: number;
  offset: number;
  visits: Visit[];
}
